### ISSUE TITLE
FIIII LEE EL FINAL DEL CHAT

### ISSUE THREAD

**Issue by AzazelHD** [FiammaMuscari/pepe-stickerly#2]
LEE EL FINAL DE TU CHATTTTTTTTTT ESTAS COMO 30 MINS ATRAS. YA TE LO SOLUCIONÉ, (UNA PARTE), PERO LEEMEEEEEEEEEEEEEEEEEEEEE

**Comment by FiammaMuscari** [comment]
sos un genio Azazelll hablame al privado!!

**Comment by AzazelHD** [comment]
no me deja jasjjassaj me pone que tienes los susurros desactivados :( me tienes que hablar tu :c
